default:
  statusbar: false
  browser_spellcheck: true
  convert_urls: false
  width: "100%"
  menubar: false
  plugins: "autolink paste fullscreen code link anchor lists hr"
  toolbar_items_size: 'small'
  toolbar1: "cut copy paste searchreplace | undo redo | removeformat | fullscreen code"
  toolbar2: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent blockquote | link unlink anchor | hr"
  content_css: /css/tinymce.css
  paste_auto_cleanup_on_paste: true
  paste_remove_spans: true
  paste_strip_class_attributes: 'mso'

advanced:
  statusbar: false
  browser_spellcheck: true
  convert_urls: false
  width: "100%"
  theme_modern_blockformats: "p,h1,h2,h3,h4,h5,h6,blockquote,div,code"
  menubar: false
  plugins: "autolink paste fullscreen table code link anchor lists hr sh4tinymce"
  toolbar_items_size: 'small'
  toolbar1: "cut copy paste searchreplace | undo redo | removeformat | fullscreen code"
  toolbar2: "formatselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent blockquote | link unlink anchor | hr | table | sh4tinymce"
  content_css: ['/css/tinymce.css', '/assets/api.css']
  paste_auto_cleanup_on_paste: true
  paste_remove_spans: true
  paste_strip_class_attributes: 'mso'
